// This file is auto generated by Rollout.io SDK during application build process, it should be committed to you repository as part of your code. For more info please checkout the FAQ at http://support.rollout.io

#if defined(__LP64__) && __LP64__
# define CGFLOAT_TYPE double
# define CGFLOAT_IS_DOUBLE 1
# define CGFLOAT_MIN DBL_MIN
# define CGFLOAT_MAX DBL_MAX
#else
# define CGFLOAT_TYPE float
# define CGFLOAT_IS_DOUBLE 0
# define CGFLOAT_MIN FLT_MIN
# define CGFLOAT_MAX FLT_MAX
#endif
typedef CGFLOAT_TYPE CGFloat;

#if !defined(OBJC_HIDE_64) && TARGET_OS_IPHONE && __LP64__
typedef bool BOOL;
#else
typedef signed char BOOL;
#endif

typedef struct __rollout_dummy_struct__ylHf5PWUd9V7o6wGLwf3J4w1Aak {
  CGFloat a;
  CGFloat b;
  CGFloat c;
  CGFloat d;
  CGFloat tx;
  CGFloat ty;
} __rollout_dummy_struct__ylHf5PWUd9V7o6wGLwf3J4w1Aak;
typedef struct __rollout_dummy_struct__Kg1pzEDSP8Yex63EDkMoKFRb_h4 {
  CGFloat width;
  CGFloat height;
} __rollout_dummy_struct__Kg1pzEDSP8Yex63EDkMoKFRb_h4;
typedef struct __rollout_dummy_struct__IXvVpDhVIAT4DPy7Erk5nSWcznk {
  CGFloat x;
  CGFloat y;
} __rollout_dummy_struct__IXvVpDhVIAT4DPy7Erk5nSWcznk;
typedef struct __rollout_dummy_struct__W9ipxW$ytjq$Lh2qB_boMyv6Chc {
  __rollout_dummy_struct__IXvVpDhVIAT4DPy7Erk5nSWcznk origin;
  __rollout_dummy_struct__Kg1pzEDSP8Yex63EDkMoKFRb_h4 size;
} __rollout_dummy_struct__W9ipxW$ytjq$Lh2qB_boMyv6Chc;
typedef struct __rollout_dummy_struct__GHuWOX3oOHfwVHsZCzXYetk81W8 {
  __rollout_dummy_struct__Kg1pzEDSP8Yex63EDkMoKFRb_h4 contentSize;
  __rollout_dummy_struct__W9ipxW$ytjq$Lh2qB_boMyv6Chc likeButtonFrame;
  __rollout_dummy_struct__W9ipxW$ytjq$Lh2qB_boMyv6Chc auxiliaryViewFrame;
} __rollout_dummy_struct__GHuWOX3oOHfwVHsZCzXYetk81W8;
typedef struct __rollout_dummy_struct__ZtUEj8ysoQSyxiH5$CeflaupHqk {
  long long value;
  int timescale;
  __rollout_enum flags;
  long long epoch;
} __rollout_dummy_struct__ZtUEj8ysoQSyxiH5$CeflaupHqk;
typedef struct __rollout_dummy_struct__D5dusVdWOlVyabEzby8G2F77Wtc {
  __rollout_dummy_struct__ZtUEj8ysoQSyxiH5$CeflaupHqk start;
  __rollout_dummy_struct__ZtUEj8ysoQSyxiH5$CeflaupHqk duration;
} __rollout_dummy_struct__D5dusVdWOlVyabEzby8G2F77Wtc;
typedef struct __rollout_dummy_struct__1B8MiYzNNkshtXqsECJ5LSNnVQs {
  double width;
  double height;
} __rollout_dummy_struct__1B8MiYzNNkshtXqsECJ5LSNnVQs;
typedef struct __rollout_dummy_struct__h4Y3OQy7IUvUhprbWZ1ZvbgAMjA {
  __rollout_dummy_struct__D5dusVdWOlVyabEzby8G2F77Wtc source;
  __rollout_dummy_struct__D5dusVdWOlVyabEzby8G2F77Wtc target;
} __rollout_dummy_struct__h4Y3OQy7IUvUhprbWZ1ZvbgAMjA;
typedef struct __rollout_dummy_struct__PmDF8pTlRPF4YSGP4FoTnrYnMH8 {
  float redGain;
  float greenGain;
  float blueGain;
} __rollout_dummy_struct__PmDF8pTlRPF4YSGP4FoTnrYnMH8;
typedef struct __rollout_dummy_struct__k$63xrfGHT0Pv5v_lBvIfdIQKgM {
  double latitude;
  double longitude;
} __rollout_dummy_struct__k$63xrfGHT0Pv5v_lBvIfdIQKgM;
typedef struct __rollout_dummy_struct__WbSq9MJru5kW4G_Awt5HPO7HsHY {
  double latitudeDelta;
  double longitudeDelta;
} __rollout_dummy_struct__WbSq9MJru5kW4G_Awt5HPO7HsHY;
typedef struct __rollout_dummy_struct__vuwJ$TcizkCqdHc45DQpw5zSwPQ {
  __rollout_dummy_struct__k$63xrfGHT0Pv5v_lBvIfdIQKgM center;
  __rollout_dummy_struct__WbSq9MJru5kW4G_Awt5HPO7HsHY span;
} __rollout_dummy_struct__vuwJ$TcizkCqdHc45DQpw5zSwPQ;
typedef struct __rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0 {
  unsigned long location;
  unsigned long length;
} __rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0;
typedef struct __rollout_dummy_struct__WFhRnNhCUGZ4uns9BMziyqDHatE {
  CGFloat m11;
  CGFloat m12;
  CGFloat m13;
  CGFloat m14;
  CGFloat m21;
  CGFloat m22;
  CGFloat m23;
  CGFloat m24;
  CGFloat m31;
  CGFloat m32;
  CGFloat m33;
  CGFloat m34;
  CGFloat m41;
  CGFloat m42;
  CGFloat m43;
  CGFloat m44;
} __rollout_dummy_struct__WFhRnNhCUGZ4uns9BMziyqDHatE;
typedef struct __rollout_dummy_struct__sD8OsQF$ImNMG2ES2KKGwrsVpgo {
  long x;
  long y;
} __rollout_dummy_struct__sD8OsQF$ImNMG2ES2KKGwrsVpgo;
typedef struct __rollout_dummy_struct___gMr7GeVS2ryn5S2nxOPon1oBgw {
  CGFloat start;
  CGFloat length;
} __rollout_dummy_struct___gMr7GeVS2ryn5S2nxOPon1oBgw;
typedef struct __rollout_dummy_struct__GNGmtf0vkNE680pJ2CJQvTQWJo8 {
  double x;
  double y;
} __rollout_dummy_struct__GNGmtf0vkNE680pJ2CJQvTQWJo8;
typedef struct __rollout_dummy_struct__nluDUUtnntc77b5qjvlCXRhwYtw {
  CGFloat location;
  CGFloat length;
} __rollout_dummy_struct__nluDUUtnntc77b5qjvlCXRhwYtw;
typedef struct __rollout_dummy_struct__ZssiGLMM9VI_EtRScogFvzRYVIw {
  CGFloat dx;
  CGFloat dy;
} __rollout_dummy_struct__ZssiGLMM9VI_EtRScogFvzRYVIw;
typedef struct __rollout_dummy_struct__JcpyGEiQLemXSZIoKgDk4xHZfkA {
  __rollout_dummy_struct__GNGmtf0vkNE680pJ2CJQvTQWJo8 origin;
  __rollout_dummy_struct__1B8MiYzNNkshtXqsECJ5LSNnVQs size;
} __rollout_dummy_struct__JcpyGEiQLemXSZIoKgDk4xHZfkA;
typedef struct __rollout_dummy_struct__Mc97o5fdTlN043SQIt84bABmZj0 {
  long location;
  long length;
} __rollout_dummy_struct__Mc97o5fdTlN043SQIt84bABmZj0;
typedef struct __rollout_dummy_struct__oGJjIRDwvikGc$VmbTzB7mtlze8 {
  CGFloat horizontal;
  CGFloat vertical;
} __rollout_dummy_struct__oGJjIRDwvikGc$VmbTzB7mtlze8;
typedef struct __rollout_dummy_struct__jviU81zjFf3q9k1qOLfWJKJwUdk {
  float x;
  float y;
} __rollout_dummy_struct__jviU81zjFf3q9k1qOLfWJKJwUdk;
typedef struct __rollout_dummy_struct__mSHPEsPe28phFBQPXD5Jz7dF_lI {
  CGFloat top;
  CGFloat left;
  CGFloat bottom;
  CGFloat right;
} __rollout_dummy_struct__mSHPEsPe28phFBQPXD5Jz7dF_lI;
typedef struct __rollout_dummy_struct___r1mw5_eDSDuKYvcNFSkfl6zMzk {
  float temperature;
  float tint;
} __rollout_dummy_struct___r1mw5_eDSDuKYvcNFSkfl6zMzk;
typedef struct __rollout_dummy_struct__zCAWsL3voSvlrUFV0hHzxtU$mSY {
  CGFloat top;
  CGFloat left;
  CGFloat bottom;
  CGFloat right;
} __rollout_dummy_struct__zCAWsL3voSvlrUFV0hHzxtU$mSY;
typedef struct __rollout_dummy_struct__YYhx_ptwXiT1ZIVQ0XCyCc8zoao {
  CGFloat a;
  CGFloat b;
  CGFloat c;
  CGFloat d;
  CGFloat tx;
  CGFloat ty;
} __rollout_dummy_struct__YYhx_ptwXiT1ZIVQ0XCyCc8zoao;
typedef struct __rollout_dummy_struct__CNF3_tkyha3OzN6PuQLKq9ganWc {
  int x;
  int y;
} __rollout_dummy_struct__CNF3_tkyha3OzN6PuQLKq9ganWc;
typedef struct __rollout_dummy_struct__RddRZw0r3SfDjJVyimz$o$RGb5A {
  long location;
  long length;
} __rollout_dummy_struct__RddRZw0r3SfDjJVyimz$o$RGb5A;
typedef struct __rollout_dummy_struct__R2avCXJVvq_97r2996lkLvKT2Fs {
  CGFloat x;
  CGFloat y;
} __rollout_dummy_struct__R2avCXJVvq_97r2996lkLvKT2Fs;
typedef struct __rollout_dummy_struct__clAxoRtDAaGXUsgvOYmN_G0UQkM {
  CGFloat width;
  CGFloat height;
} __rollout_dummy_struct__clAxoRtDAaGXUsgvOYmN_G0UQkM;
typedef struct __rollout_dummy_struct__w3oOoi0MUVGIXS$S0Q2ltCT3k28 {
  CGFloat start;
  CGFloat length;
} __rollout_dummy_struct__w3oOoi0MUVGIXS$S0Q2ltCT3k28;
typedef struct __rollout_dummy_struct__f1UVziccq$g$G3CJuEbQxqagrOc {
  CGFloat dx;
  CGFloat dy;
} __rollout_dummy_struct__f1UVziccq$g$G3CJuEbQxqagrOc;
typedef struct __rollout_dummy_struct__r5ouMjAKmzEbgcmRq5DIfiumCzg {
  unsigned int location;
  unsigned int length;
} __rollout_dummy_struct__r5ouMjAKmzEbgcmRq5DIfiumCzg;
typedef struct __rollout_dummy_struct__Ezp4PnnU5vfm3Ep2lu6VDq0G07s {
  CGFloat horizontal;
  CGFloat vertical;
} __rollout_dummy_struct__Ezp4PnnU5vfm3Ep2lu6VDq0G07s;
typedef struct __rollout_dummy_struct__G8qSdk0juzppWFA1fsFKyoNCPus {
  CGFloat location;
  CGFloat length;
} __rollout_dummy_struct__G8qSdk0juzppWFA1fsFKyoNCPus;
typedef struct __rollout_dummy_struct__jc9slQ7iaEAkp24qe0AZIP$kOCU {
  __rollout_dummy_struct__R2avCXJVvq_97r2996lkLvKT2Fs origin;
  __rollout_dummy_struct__clAxoRtDAaGXUsgvOYmN_G0UQkM size;
} __rollout_dummy_struct__jc9slQ7iaEAkp24qe0AZIP$kOCU;
typedef struct __rollout_dummy_struct__5RZ0cxpFDzoSrICiR4kUL_rkPN4 {
  __rollout_dummy_struct__clAxoRtDAaGXUsgvOYmN_G0UQkM contentSize;
  __rollout_dummy_struct__jc9slQ7iaEAkp24qe0AZIP$kOCU likeButtonFrame;
  __rollout_dummy_struct__jc9slQ7iaEAkp24qe0AZIP$kOCU auxiliaryViewFrame;
} __rollout_dummy_struct__5RZ0cxpFDzoSrICiR4kUL_rkPN4;
typedef struct __rollout_dummy_struct__FwPK6xDjiMLrUxS5U0iAr1jKLN8 {
  CGFloat m11;
  CGFloat m12;
  CGFloat m13;
  CGFloat m14;
  CGFloat m21;
  CGFloat m22;
  CGFloat m23;
  CGFloat m24;
  CGFloat m31;
  CGFloat m32;
  CGFloat m33;
  CGFloat m34;
  CGFloat m41;
  CGFloat m42;
  CGFloat m43;
  CGFloat m44;
} __rollout_dummy_struct__FwPK6xDjiMLrUxS5U0iAr1jKLN8;
