// This file is auto generated by Rollout.io SDK during application build process, it should be committed to you repository as part of your code. For more info please checkout the FAQ at http://support.rollout.io

#import <Rollout/private/RolloutDynamic.h>
#import <Rollout/private/RolloutInvocation.h>
#import <Rollout/private/RolloutTypeWrapper.h>
#import <Rollout/private/RolloutInvocationsListFactory.h>
#import <Rollout/private/RolloutErrors.h>
#import <Rollout/private/RolloutMethodId.h>
#import <Rollout/private/RolloutTweakId.h>
#import <Rollout/private/RolloutConfiguration.h>
#import <objc/objc.h>

#import "RolloutDynamic_structs.h"

@implementation RolloutDynamic(blocks_4)


- (id)blockFor_instanceMethod_BOOL_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^BOOL(id rcv) {
    BOOL (*originalFunction)(id, SEL) = (void *) originalImplementation;
    NSArray *originalArguments = @[];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithBool:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector))];
    }];

    return result.boolValue;
  };
}

- (id)blockFor_classMethod_ULong_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^unsigned long(id rcv) {
    unsigned long (*originalFunction)(id, SEL) = (void *) originalImplementation;
    NSArray *originalArguments = @[];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithULong:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector))];
    }];

    return result.uLongValue;
  };
}

- (id)blockFor_instanceMethod_Void___BOOL_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^void(id rcv, BOOL arg0) {
    void (*originalFunction)(id, SEL, BOOL) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithBool:arg0], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).boolValue); return [[RolloutTypeWrapper alloc] initWithVoid];
    }];

    
  };
}

- (id)blockFor_instanceMethod_ObjCObjectPointer___ObjCObjectPointer___ObjCObjectPointer___BOOL___BOOL_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^id(id rcv, id arg0, id arg1, BOOL arg2, BOOL arg3) {
    id (*originalFunction)(id, SEL, id, id, BOOL, BOOL) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg1], 
     [[RolloutTypeWrapper alloc] initWithBool:arg2], 
     [[RolloutTypeWrapper alloc] initWithBool:arg3], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[1]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[2]).boolValue, ((RolloutTypeWrapper*)arguments[3]).boolValue)];
    }];

    return result.objCObjectPointerValue;
  };
}

- (id)blockFor_classMethod_Int___Pointer_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^int(id rcv, void* arg0) {
    int (*originalFunction)(id, SEL, void*) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithPointer:arg0], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithInt:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).pointerValue)];
    }];

    return result.intValue;
  };
}

- (id)blockFor_classMethod_ObjCObjectPointer___ObjCObjectPointer___BOOL_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^id(id rcv, id arg0, BOOL arg1) {
    id (*originalFunction)(id, SEL, id, BOOL) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithBool:arg1], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[1]).boolValue)];
    }];

    return result.objCObjectPointerValue;
  };
}

- (id)blockFor_instanceMethod_ObjCObjectPointer___Enum_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^id(id rcv, __rollout_enum arg0) {
    id (*originalFunction)(id, SEL, __rollout_enum) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithEnum:arg0], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).enumValue)];
    }];

    return result.objCObjectPointerValue;
  };
}

- (id)blockFor_classMethod_BOOL___Int_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^BOOL(id rcv, int arg0) {
    BOOL (*originalFunction)(id, SEL, int) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithInt:arg0], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithBool:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).intValue)];
    }];

    return result.boolValue;
  };
}

- (id)blockFor_instanceMethod_Enum___ObjCObjectPointer_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^__rollout_enum(id rcv, id arg0) {
    __rollout_enum (*originalFunction)(id, SEL, id) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithEnum:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue)];
    }];

    return result.enumValue;
  };
}

- (id)blockFor_instanceMethod_Void___ObjCObjectPointer___BOOL___ObjCObjectPointer_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^void(id rcv, id arg0, BOOL arg1, id arg2) {
    void (*originalFunction)(id, SEL, id, BOOL, id) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithBool:arg1], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg2], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[1]).boolValue, ((RolloutTypeWrapper*)arguments[2]).objCObjectPointerValue); return [[RolloutTypeWrapper alloc] initWithVoid];
    }];

    
  };
}

- (id)blockFor_classMethod_ObjCObjectPointer___Int___ObjCObjectPointer_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^id(id rcv, int arg0, id arg1) {
    id (*originalFunction)(id, SEL, int, id) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithInt:arg0], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg1], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).intValue, ((RolloutTypeWrapper*)arguments[1]).objCObjectPointerValue)];
    }];

    return result.objCObjectPointerValue;
  };
}

- (id)blockFor_instanceMethod_Void___Record_struct_RolloutSpace_CATransform3D_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^void(id rcv, __rollout_dummy_struct__WFhRnNhCUGZ4uns9BMziyqDHatE arg0) {
    void (*originalFunction)(id, SEL, __rollout_dummy_struct__WFhRnNhCUGZ4uns9BMziyqDHatE) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithRecordPointer:&arg0 ofSize:sizeof(__rollout_dummy_struct__WFhRnNhCUGZ4uns9BMziyqDHatE) shouldBeFreedInDealloc:NO], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), *(__rollout_dummy_struct__WFhRnNhCUGZ4uns9BMziyqDHatE*)((RolloutTypeWrapper*)arguments[0]).recordPointer); return [[RolloutTypeWrapper alloc] initWithVoid];
    }];

    
  };
}

- (id)blockFor_instanceMethod_Record_struct_RolloutSpace_CATransform3D_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^__rollout_dummy_struct__WFhRnNhCUGZ4uns9BMziyqDHatE(id rcv) {
    __rollout_dummy_struct__WFhRnNhCUGZ4uns9BMziyqDHatE (*originalFunction)(id, SEL) = (void *) originalImplementation;
    NSArray *originalArguments = @[];
    __block __rollout_dummy_struct__WFhRnNhCUGZ4uns9BMziyqDHatE record;
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        record = originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector));
        return [[RolloutTypeWrapper alloc] initWithRecordPointer:&record ofSize:sizeof(__rollout_dummy_struct__WFhRnNhCUGZ4uns9BMziyqDHatE) shouldBeFreedInDealloc:NO];
    }];

    return *(__rollout_dummy_struct__WFhRnNhCUGZ4uns9BMziyqDHatE *)result.recordPointer;
  };
}

- (id)blockFor_instanceMethod_ObjCObjectPointer___Int___Int___Pointer___Int_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^id(id rcv, int arg0, int arg1, void* arg2, int arg3) {
    id (*originalFunction)(id, SEL, int, int, void*, int) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithInt:arg0], 
     [[RolloutTypeWrapper alloc] initWithInt:arg1], 
     [[RolloutTypeWrapper alloc] initWithPointer:arg2], 
     [[RolloutTypeWrapper alloc] initWithInt:arg3], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).intValue, ((RolloutTypeWrapper*)arguments[1]).intValue, ((RolloutTypeWrapper*)arguments[2]).pointerValue, ((RolloutTypeWrapper*)arguments[3]).intValue)];
    }];

    return result.objCObjectPointerValue;
  };
}

- (id)blockFor_instanceMethod_ObjCObjectPointer___ObjCObjectPointer___ObjCObjectPointer___Record_struct_RolloutSpace_CGSize_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^id(id rcv, id arg0, id arg1, __rollout_dummy_struct__Kg1pzEDSP8Yex63EDkMoKFRb_h4 arg2) {
    id (*originalFunction)(id, SEL, id, id, __rollout_dummy_struct__Kg1pzEDSP8Yex63EDkMoKFRb_h4) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg1], 
     [[RolloutTypeWrapper alloc] initWithRecordPointer:&arg2 ofSize:sizeof(__rollout_dummy_struct__Kg1pzEDSP8Yex63EDkMoKFRb_h4) shouldBeFreedInDealloc:NO], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[1]).objCObjectPointerValue, *(__rollout_dummy_struct__Kg1pzEDSP8Yex63EDkMoKFRb_h4*)((RolloutTypeWrapper*)arguments[2]).recordPointer)];
    }];

    return result.objCObjectPointerValue;
  };
}

- (id)blockFor_instanceMethod_ObjCObjectPointer___Record_struct_RolloutSpace_UIEdgeInsets_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^id(id rcv, __rollout_dummy_struct__mSHPEsPe28phFBQPXD5Jz7dF_lI arg0) {
    id (*originalFunction)(id, SEL, __rollout_dummy_struct__mSHPEsPe28phFBQPXD5Jz7dF_lI) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithRecordPointer:&arg0 ofSize:sizeof(__rollout_dummy_struct__mSHPEsPe28phFBQPXD5Jz7dF_lI) shouldBeFreedInDealloc:NO], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), *(__rollout_dummy_struct__mSHPEsPe28phFBQPXD5Jz7dF_lI*)((RolloutTypeWrapper*)arguments[0]).recordPointer)];
    }];

    return result.objCObjectPointerValue;
  };
}

- (id)blockFor_classMethod_ObjCObjectPointer___BOOL___ObjCObjectPointer___Pointer_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^id(id rcv, BOOL arg0, id arg1, void* arg2) {
    id (*originalFunction)(id, SEL, BOOL, id, void*) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithBool:arg0], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg1], 
     [[RolloutTypeWrapper alloc] initWithPointer:arg2], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).boolValue, ((RolloutTypeWrapper*)arguments[1]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[2]).pointerValue)];
    }];

    return result.objCObjectPointerValue;
  };
}

- (id)blockFor_instanceMethod_Void___ObjCObjectPointer___Int_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^void(id rcv, id arg0, int arg1) {
    void (*originalFunction)(id, SEL, id, int) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithInt:arg1], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[1]).intValue); return [[RolloutTypeWrapper alloc] initWithVoid];
    }];

    
  };
}

- (id)blockFor_instanceMethod_Void___BlockPointer___Long_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^void(id rcv, id arg0, long arg1) {
    void (*originalFunction)(id, SEL, id, long) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithBlockPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithLong:arg1], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).blockPointerValue, ((RolloutTypeWrapper*)arguments[1]).longValue); return [[RolloutTypeWrapper alloc] initWithVoid];
    }];

    
  };
}

- (id)blockFor_classMethod_ObjCObjectPointer___ObjCObjectPointer___ObjCObjectPointer___BOOL___BOOL_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^id(id rcv, id arg0, id arg1, BOOL arg2, BOOL arg3) {
    id (*originalFunction)(id, SEL, id, id, BOOL, BOOL) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg1], 
     [[RolloutTypeWrapper alloc] initWithBool:arg2], 
     [[RolloutTypeWrapper alloc] initWithBool:arg3], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[1]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[2]).boolValue, ((RolloutTypeWrapper*)arguments[3]).boolValue)];
    }];

    return result.objCObjectPointerValue;
  };
}

- (id)blockFor_instanceMethod_Void___Pointer___Record_struct_RolloutSpace_CGRect___ObjCObjectPointer___Record_struct_RolloutSpace_ChartRange___Record_struct_RolloutSpace_ChartRange_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^void(id rcv, void* arg0, __rollout_dummy_struct__W9ipxW$ytjq$Lh2qB_boMyv6Chc arg1, id arg2, __rollout_dummy_struct___gMr7GeVS2ryn5S2nxOPon1oBgw arg3, __rollout_dummy_struct___gMr7GeVS2ryn5S2nxOPon1oBgw arg4) {
    void (*originalFunction)(id, SEL, void*, __rollout_dummy_struct__W9ipxW$ytjq$Lh2qB_boMyv6Chc, id, __rollout_dummy_struct___gMr7GeVS2ryn5S2nxOPon1oBgw, __rollout_dummy_struct___gMr7GeVS2ryn5S2nxOPon1oBgw) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithRecordPointer:&arg1 ofSize:sizeof(__rollout_dummy_struct__W9ipxW$ytjq$Lh2qB_boMyv6Chc) shouldBeFreedInDealloc:NO], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg2], 
     [[RolloutTypeWrapper alloc] initWithRecordPointer:&arg3 ofSize:sizeof(__rollout_dummy_struct___gMr7GeVS2ryn5S2nxOPon1oBgw) shouldBeFreedInDealloc:NO], 
     [[RolloutTypeWrapper alloc] initWithRecordPointer:&arg4 ofSize:sizeof(__rollout_dummy_struct___gMr7GeVS2ryn5S2nxOPon1oBgw) shouldBeFreedInDealloc:NO], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).pointerValue, *(__rollout_dummy_struct__W9ipxW$ytjq$Lh2qB_boMyv6Chc*)((RolloutTypeWrapper*)arguments[1]).recordPointer, ((RolloutTypeWrapper*)arguments[2]).objCObjectPointerValue, *(__rollout_dummy_struct___gMr7GeVS2ryn5S2nxOPon1oBgw*)((RolloutTypeWrapper*)arguments[3]).recordPointer, *(__rollout_dummy_struct___gMr7GeVS2ryn5S2nxOPon1oBgw*)((RolloutTypeWrapper*)arguments[4]).recordPointer); return [[RolloutTypeWrapper alloc] initWithVoid];
    }];

    
  };
}

- (id)blockFor_instanceMethod_Void___Enum___ObjCObjectPointer___ObjCObjectPointer_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^void(id rcv, __rollout_enum arg0, id arg1, id arg2) {
    void (*originalFunction)(id, SEL, __rollout_enum, id, id) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithEnum:arg0], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg1], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg2], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).enumValue, ((RolloutTypeWrapper*)arguments[1]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[2]).objCObjectPointerValue); return [[RolloutTypeWrapper alloc] initWithVoid];
    }];

    
  };
}

- (id)blockFor_instanceMethod_ObjCObjectPointer___Int___ObjCObjectPointer___Record_struct_RolloutSpace__NSRange___ObjCObjectPointer___Pointer_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^id(id rcv, int arg0, id arg1, __rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0 arg2, id arg3, void* arg4) {
    id (*originalFunction)(id, SEL, int, id, __rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0, id, void*) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithInt:arg0], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg1], 
     [[RolloutTypeWrapper alloc] initWithRecordPointer:&arg2 ofSize:sizeof(__rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0) shouldBeFreedInDealloc:NO], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg3], 
     [[RolloutTypeWrapper alloc] initWithPointer:arg4], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).intValue, ((RolloutTypeWrapper*)arguments[1]).objCObjectPointerValue, *(__rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0*)((RolloutTypeWrapper*)arguments[2]).recordPointer, ((RolloutTypeWrapper*)arguments[3]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[4]).pointerValue)];
    }];

    return result.objCObjectPointerValue;
  };
}

- (id)blockFor_instanceMethod_ObjCObjectPointer___BOOL___Int___Int___Int___Int___Int_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^id(id rcv, BOOL arg0, int arg1, int arg2, int arg3, int arg4, int arg5) {
    id (*originalFunction)(id, SEL, BOOL, int, int, int, int, int) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithBool:arg0], 
     [[RolloutTypeWrapper alloc] initWithInt:arg1], 
     [[RolloutTypeWrapper alloc] initWithInt:arg2], 
     [[RolloutTypeWrapper alloc] initWithInt:arg3], 
     [[RolloutTypeWrapper alloc] initWithInt:arg4], 
     [[RolloutTypeWrapper alloc] initWithInt:arg5], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).boolValue, ((RolloutTypeWrapper*)arguments[1]).intValue, ((RolloutTypeWrapper*)arguments[2]).intValue, ((RolloutTypeWrapper*)arguments[3]).intValue, ((RolloutTypeWrapper*)arguments[4]).intValue, ((RolloutTypeWrapper*)arguments[5]).intValue)];
    }];

    return result.objCObjectPointerValue;
  };
}

- (id)blockFor_instanceMethod_Void___CGFloat___CGFloat___CGFloat_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^void(id rcv, CGFloat arg0, CGFloat arg1, CGFloat arg2) {
    void (*originalFunction)(id, SEL, CGFloat, CGFloat, CGFloat) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithDouble:arg0], 
     [[RolloutTypeWrapper alloc] initWithDouble:arg1], 
     [[RolloutTypeWrapper alloc] initWithDouble:arg2], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).doubleValue, ((RolloutTypeWrapper*)arguments[1]).doubleValue, ((RolloutTypeWrapper*)arguments[2]).doubleValue); return [[RolloutTypeWrapper alloc] initWithVoid];
    }];

    
  };
}

- (id)blockFor_instanceMethod_BOOL___ObjCObjectPointer___ObjCObjectPointer___ObjCObjectPointer___ObjCObjectPointer___Pointer_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^BOOL(id rcv, id arg0, id arg1, id arg2, id arg3, void* arg4) {
    BOOL (*originalFunction)(id, SEL, id, id, id, id, void*) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg1], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg2], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg3], 
     [[RolloutTypeWrapper alloc] initWithPointer:arg4], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithBool:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[1]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[2]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[3]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[4]).pointerValue)];
    }];

    return result.boolValue;
  };
}

- (id)blockFor_classMethod_ObjCObjectPointer___UInt_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^id(id rcv, unsigned int arg0) {
    id (*originalFunction)(id, SEL, unsigned int) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithUInt:arg0], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).uIntValue)];
    }];

    return result.objCObjectPointerValue;
  };
}

- (id)blockFor_instanceMethod_ObjCObjectPointer___Long___Long___ObjCObjectPointer___ObjCObjectPointer_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^id(id rcv, long arg0, long arg1, id arg2, id arg3) {
    id (*originalFunction)(id, SEL, long, long, id, id) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithLong:arg0], 
     [[RolloutTypeWrapper alloc] initWithLong:arg1], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg2], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg3], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).longValue, ((RolloutTypeWrapper*)arguments[1]).longValue, ((RolloutTypeWrapper*)arguments[2]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[3]).objCObjectPointerValue)];
    }];

    return result.objCObjectPointerValue;
  };
}

- (id)blockFor_instanceMethod_ObjCObjectPointer___BOOL___BOOL_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^id(id rcv, BOOL arg0, BOOL arg1) {
    id (*originalFunction)(id, SEL, BOOL, BOOL) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithBool:arg0], 
     [[RolloutTypeWrapper alloc] initWithBool:arg1], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).boolValue, ((RolloutTypeWrapper*)arguments[1]).boolValue)];
    }];

    return result.objCObjectPointerValue;
  };
}

- (id)blockFor_instanceMethod_Void___ObjCObjectPointer___ObjCObjectPointer___ULong_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^void(id rcv, id arg0, id arg1, unsigned long arg2) {
    void (*originalFunction)(id, SEL, id, id, unsigned long) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg1], 
     [[RolloutTypeWrapper alloc] initWithULong:arg2], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[1]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[2]).uLongValue); return [[RolloutTypeWrapper alloc] initWithVoid];
    }];

    
  };
}

- (id)blockFor_classMethod_ObjCObjectPointer___ObjCObjectPointer___ObjCObjectPointer___ObjCObjectPointer___BOOL___Int___Int_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^id(id rcv, id arg0, id arg1, id arg2, BOOL arg3, int arg4, int arg5) {
    id (*originalFunction)(id, SEL, id, id, id, BOOL, int, int) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg1], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg2], 
     [[RolloutTypeWrapper alloc] initWithBool:arg3], 
     [[RolloutTypeWrapper alloc] initWithInt:arg4], 
     [[RolloutTypeWrapper alloc] initWithInt:arg5], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[1]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[2]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[3]).boolValue, ((RolloutTypeWrapper*)arguments[4]).intValue, ((RolloutTypeWrapper*)arguments[5]).intValue)];
    }];

    return result.objCObjectPointerValue;
  };
}

- (id)blockFor_classMethod_ObjCObjectPointer___ObjCObjectPointer___Int___Int___BOOL___Int___Int___Int___Int_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^id(id rcv, id arg0, int arg1, int arg2, BOOL arg3, int arg4, int arg5, int arg6, int arg7) {
    id (*originalFunction)(id, SEL, id, int, int, BOOL, int, int, int, int) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithInt:arg1], 
     [[RolloutTypeWrapper alloc] initWithInt:arg2], 
     [[RolloutTypeWrapper alloc] initWithBool:arg3], 
     [[RolloutTypeWrapper alloc] initWithInt:arg4], 
     [[RolloutTypeWrapper alloc] initWithInt:arg5], 
     [[RolloutTypeWrapper alloc] initWithInt:arg6], 
     [[RolloutTypeWrapper alloc] initWithInt:arg7], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[1]).intValue, ((RolloutTypeWrapper*)arguments[2]).intValue, ((RolloutTypeWrapper*)arguments[3]).boolValue, ((RolloutTypeWrapper*)arguments[4]).intValue, ((RolloutTypeWrapper*)arguments[5]).intValue, ((RolloutTypeWrapper*)arguments[6]).intValue, ((RolloutTypeWrapper*)arguments[7]).intValue)];
    }];

    return result.objCObjectPointerValue;
  };
}

- (id)blockFor_instanceMethod_Void___ObjCObjectPointer___ObjCObjectPointer___ObjCObjectPointer___ObjCObjectPointer___BlockPointer___BlockPointer_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^void(id rcv, id arg0, id arg1, id arg2, id arg3, id arg4, id arg5) {
    void (*originalFunction)(id, SEL, id, id, id, id, id, id) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg1], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg2], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg3], 
     [[RolloutTypeWrapper alloc] initWithBlockPointer:arg4], 
     [[RolloutTypeWrapper alloc] initWithBlockPointer:arg5], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[1]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[2]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[3]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[4]).blockPointerValue, ((RolloutTypeWrapper*)arguments[5]).blockPointerValue); return [[RolloutTypeWrapper alloc] initWithVoid];
    }];

    
  };
}

- (id)blockFor_instanceMethod_CGFloat___Enum_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^CGFloat(id rcv, __rollout_enum arg0) {
    CGFloat (*originalFunction)(id, SEL, __rollout_enum) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithEnum:arg0], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithDouble:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).enumValue)];
    }];

    return result.doubleValue;
  };
}

- (id)blockFor_instanceMethod_Void___ObjCObjectPointer___ObjCObjectPointer___CGFloat___CGFloat_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^void(id rcv, id arg0, id arg1, CGFloat arg2, CGFloat arg3) {
    void (*originalFunction)(id, SEL, id, id, CGFloat, CGFloat) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg1], 
     [[RolloutTypeWrapper alloc] initWithDouble:arg2], 
     [[RolloutTypeWrapper alloc] initWithDouble:arg3], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[1]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[2]).doubleValue, ((RolloutTypeWrapper*)arguments[3]).doubleValue); return [[RolloutTypeWrapper alloc] initWithVoid];
    }];

    
  };
}

- (id)blockFor_classMethod_CGFloat___Long_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^CGFloat(id rcv, long arg0) {
    CGFloat (*originalFunction)(id, SEL, long) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithLong:arg0], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithDouble:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).longValue)];
    }];

    return result.doubleValue;
  };
}

- (id)blockFor_instanceMethod_CGFloat___ULong_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^CGFloat(id rcv, unsigned long arg0) {
    CGFloat (*originalFunction)(id, SEL, unsigned long) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithULong:arg0], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithDouble:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).uLongValue)];
    }];

    return result.doubleValue;
  };
}

- (id)blockFor_instanceMethod_Void___ObjCObjectPointer___BOOL___BOOL___BOOL_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^void(id rcv, id arg0, BOOL arg1, BOOL arg2, BOOL arg3) {
    void (*originalFunction)(id, SEL, id, BOOL, BOOL, BOOL) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithBool:arg1], 
     [[RolloutTypeWrapper alloc] initWithBool:arg2], 
     [[RolloutTypeWrapper alloc] initWithBool:arg3], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[1]).boolValue, ((RolloutTypeWrapper*)arguments[2]).boolValue, ((RolloutTypeWrapper*)arguments[3]).boolValue); return [[RolloutTypeWrapper alloc] initWithVoid];
    }];

    
  };
}

- (id)blockFor_classMethod_LongLong___ULongLong___ULongLong_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^long long(id rcv, unsigned long long arg0, unsigned long long arg1) {
    long long (*originalFunction)(id, SEL, unsigned long long, unsigned long long) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithULongLong:arg0], 
     [[RolloutTypeWrapper alloc] initWithULongLong:arg1], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithLongLong:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).uLongLongValue, ((RolloutTypeWrapper*)arguments[1]).uLongLongValue)];
    }];

    return result.longLongValue;
  };
}

- (id)blockFor_classMethod_Void___ObjCObjectPointer___ObjCObjectPointer___BlockPointer___BOOL_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^void(id rcv, id arg0, id arg1, id arg2, BOOL arg3) {
    void (*originalFunction)(id, SEL, id, id, id, BOOL) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg1], 
     [[RolloutTypeWrapper alloc] initWithBlockPointer:arg2], 
     [[RolloutTypeWrapper alloc] initWithBool:arg3], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[1]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[2]).blockPointerValue, ((RolloutTypeWrapper*)arguments[3]).boolValue); return [[RolloutTypeWrapper alloc] initWithVoid];
    }];

    
  };
}

- (id)blockFor_instanceMethod_Void___Enum___BlockPointer_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^void(id rcv, __rollout_enum arg0, id arg1) {
    void (*originalFunction)(id, SEL, __rollout_enum, id) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithEnum:arg0], 
     [[RolloutTypeWrapper alloc] initWithBlockPointer:arg1], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).enumValue, ((RolloutTypeWrapper*)arguments[1]).blockPointerValue); return [[RolloutTypeWrapper alloc] initWithVoid];
    }];

    
  };
}

- (id)blockFor_instanceMethod_Void___Enum___ObjCObjectPointer___ObjCObjectPointer___BOOL_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^void(id rcv, __rollout_enum arg0, id arg1, id arg2, BOOL arg3) {
    void (*originalFunction)(id, SEL, __rollout_enum, id, id, BOOL) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithEnum:arg0], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg1], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg2], 
     [[RolloutTypeWrapper alloc] initWithBool:arg3], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).enumValue, ((RolloutTypeWrapper*)arguments[1]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[2]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[3]).boolValue); return [[RolloutTypeWrapper alloc] initWithVoid];
    }];

    
  };
}

- (id)blockFor_instanceMethod_ObjCObjectPointer___CGFloat___Enum___Long_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^id(id rcv, CGFloat arg0, __rollout_enum arg1, long arg2) {
    id (*originalFunction)(id, SEL, CGFloat, __rollout_enum, long) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithDouble:arg0], 
     [[RolloutTypeWrapper alloc] initWithEnum:arg1], 
     [[RolloutTypeWrapper alloc] initWithLong:arg2], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).doubleValue, ((RolloutTypeWrapper*)arguments[1]).enumValue, ((RolloutTypeWrapper*)arguments[2]).longValue)];
    }];

    return result.objCObjectPointerValue;
  };
}

- (id)blockFor_classMethod_ULong___LongLong_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^unsigned long(id rcv, long long arg0) {
    unsigned long (*originalFunction)(id, SEL, long long) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithLongLong:arg0], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithULong:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).longLongValue)];
    }];

    return result.uLongValue;
  };
}

- (id)blockFor_classMethod_ObjCObjectPointer___Pointer___ULong___ObjCObjectPointer_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^id(id rcv, void* arg0, unsigned long arg1, id arg2) {
    id (*originalFunction)(id, SEL, void*, unsigned long, id) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithULong:arg1], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg2], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).pointerValue, ((RolloutTypeWrapper*)arguments[1]).uLongValue, ((RolloutTypeWrapper*)arguments[2]).objCObjectPointerValue)];
    }];

    return result.objCObjectPointerValue;
  };
}

- (id)blockFor_instanceMethod_Void___ObjCObjectPointer___ObjCObjectPointer___Double___Record_struct_RolloutSpace__NSRange_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^void(id rcv, id arg0, id arg1, double arg2, __rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0 arg3) {
    void (*originalFunction)(id, SEL, id, id, double, __rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg1], 
     [[RolloutTypeWrapper alloc] initWithDouble:arg2], 
     [[RolloutTypeWrapper alloc] initWithRecordPointer:&arg3 ofSize:sizeof(__rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0) shouldBeFreedInDealloc:NO], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[1]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[2]).doubleValue, *(__rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0*)((RolloutTypeWrapper*)arguments[3]).recordPointer); return [[RolloutTypeWrapper alloc] initWithVoid];
    }];

    
  };
}

- (id)blockFor_classMethod_Void___ObjCObjectPointer___Int___Int_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^void(id rcv, id arg0, int arg1, int arg2) {
    void (*originalFunction)(id, SEL, id, int, int) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithInt:arg1], 
     [[RolloutTypeWrapper alloc] initWithInt:arg2], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[1]).intValue, ((RolloutTypeWrapper*)arguments[2]).intValue); return [[RolloutTypeWrapper alloc] initWithVoid];
    }];

    
  };
}

- (id)blockFor_classMethod_Record_struct_RolloutSpace__NSRange___ObjCObjectPointer___Int___BOOL___Pointer___Int___Pointer_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^__rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0(id rcv, id arg0, int arg1, BOOL arg2, void* arg3, int arg4, void* arg5) {
    __rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0 (*originalFunction)(id, SEL, id, int, BOOL, void*, int, void*) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithInt:arg1], 
     [[RolloutTypeWrapper alloc] initWithBool:arg2], 
     [[RolloutTypeWrapper alloc] initWithPointer:arg3], 
     [[RolloutTypeWrapper alloc] initWithInt:arg4], 
     [[RolloutTypeWrapper alloc] initWithPointer:arg5], 
];
    __block __rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0 record;
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        record = originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[1]).intValue, ((RolloutTypeWrapper*)arguments[2]).boolValue, ((RolloutTypeWrapper*)arguments[3]).pointerValue, ((RolloutTypeWrapper*)arguments[4]).intValue, ((RolloutTypeWrapper*)arguments[5]).pointerValue);
        return [[RolloutTypeWrapper alloc] initWithRecordPointer:&record ofSize:sizeof(__rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0) shouldBeFreedInDealloc:NO];
    }];

    return *(__rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0 *)result.recordPointer;
  };
}

- (id)blockFor_classMethod_Record_struct_RolloutSpace__NSRange___ObjCObjectPointer___Int___BOOL___Pointer___Int___ObjCObjectPointer___Pointer_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^__rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0(id rcv, id arg0, int arg1, BOOL arg2, void* arg3, int arg4, id arg5, void* arg6) {
    __rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0 (*originalFunction)(id, SEL, id, int, BOOL, void*, int, id, void*) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithInt:arg1], 
     [[RolloutTypeWrapper alloc] initWithBool:arg2], 
     [[RolloutTypeWrapper alloc] initWithPointer:arg3], 
     [[RolloutTypeWrapper alloc] initWithInt:arg4], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg5], 
     [[RolloutTypeWrapper alloc] initWithPointer:arg6], 
];
    __block __rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0 record;
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        record = originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[1]).intValue, ((RolloutTypeWrapper*)arguments[2]).boolValue, ((RolloutTypeWrapper*)arguments[3]).pointerValue, ((RolloutTypeWrapper*)arguments[4]).intValue, ((RolloutTypeWrapper*)arguments[5]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[6]).pointerValue);
        return [[RolloutTypeWrapper alloc] initWithRecordPointer:&record ofSize:sizeof(__rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0) shouldBeFreedInDealloc:NO];
    }];

    return *(__rollout_dummy_struct__cO1vzwCDUNmksCug6I0KbtE_W_0 *)result.recordPointer;
  };
}

- (id)blockFor_classMethod_ObjCObjectPointer___ObjCObjectPointer___Long___Long_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^id(id rcv, id arg0, long arg1, long arg2) {
    id (*originalFunction)(id, SEL, id, long, long) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithLong:arg1], 
     [[RolloutTypeWrapper alloc] initWithLong:arg2], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[1]).longValue, ((RolloutTypeWrapper*)arguments[2]).longValue)];
    }];

    return result.objCObjectPointerValue;
  };
}

- (id)blockFor_classMethod_ObjCObjectPointer___ObjCObjectPointer___ObjCObjectPointer___ObjCObjectPointer___ObjCObjectPointer___Int_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^id(id rcv, id arg0, id arg1, id arg2, id arg3, int arg4) {
    id (*originalFunction)(id, SEL, id, id, id, id, int) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg1], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg2], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg3], 
     [[RolloutTypeWrapper alloc] initWithInt:arg4], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[1]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[2]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[3]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[4]).intValue)];
    }];

    return result.objCObjectPointerValue;
  };
}

- (id)blockFor_classMethod_ObjCObjectPointer___ObjCObjectPointer___ObjCObjectPointer___Int_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^id(id rcv, id arg0, id arg1, int arg2) {
    id (*originalFunction)(id, SEL, id, id, int) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg1], 
     [[RolloutTypeWrapper alloc] initWithInt:arg2], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[1]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[2]).intValue)];
    }];

    return result.objCObjectPointerValue;
  };
}

- (id)blockFor_instanceMethod_Void___BlockPointer___Int_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^void(id rcv, id arg0, int arg1) {
    void (*originalFunction)(id, SEL, id, int) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithBlockPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithInt:arg1], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).blockPointerValue, ((RolloutTypeWrapper*)arguments[1]).intValue); return [[RolloutTypeWrapper alloc] initWithVoid];
    }];

    
  };
}

- (id)blockFor_instanceMethod_ObjCObjectPointer___Record_CLLocationCoordinate2D___Int___ObjCObjectPointer___Int___ObjCObjectPointer_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^id(id rcv, __rollout_dummy_struct__k$63xrfGHT0Pv5v_lBvIfdIQKgM arg0, int arg1, id arg2, int arg3, id arg4) {
    id (*originalFunction)(id, SEL, __rollout_dummy_struct__k$63xrfGHT0Pv5v_lBvIfdIQKgM, int, id, int, id) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithRecordPointer:&arg0 ofSize:sizeof(__rollout_dummy_struct__k$63xrfGHT0Pv5v_lBvIfdIQKgM) shouldBeFreedInDealloc:NO], 
     [[RolloutTypeWrapper alloc] initWithInt:arg1], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg2], 
     [[RolloutTypeWrapper alloc] initWithInt:arg3], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg4], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), *(__rollout_dummy_struct__k$63xrfGHT0Pv5v_lBvIfdIQKgM*)((RolloutTypeWrapper*)arguments[0]).recordPointer, ((RolloutTypeWrapper*)arguments[1]).intValue, ((RolloutTypeWrapper*)arguments[2]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[3]).intValue, ((RolloutTypeWrapper*)arguments[4]).objCObjectPointerValue)];
    }];

    return result.objCObjectPointerValue;
  };
}

- (id)blockFor_instanceMethod_Void___ObjCObjectPointer___UInt_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^void(id rcv, id arg0, unsigned int arg1) {
    void (*originalFunction)(id, SEL, id, unsigned int) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithUInt:arg1], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[1]).uIntValue); return [[RolloutTypeWrapper alloc] initWithVoid];
    }];

    
  };
}

- (id)blockFor_classMethod_ObjCObjectPointer___Int___ObjCObjectPointer___ObjCObjectPointer___ObjCObjectPointer_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^id(id rcv, int arg0, id arg1, id arg2, id arg3) {
    id (*originalFunction)(id, SEL, int, id, id, id) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithInt:arg0], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg1], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg2], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg3], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        return [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).intValue, ((RolloutTypeWrapper*)arguments[1]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[2]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[3]).objCObjectPointerValue)];
    }];

    return result.objCObjectPointerValue;
  };
}

- (id)blockFor_instanceMethod_Void___ObjCObjectPointer___ObjCObjectPointer___ObjCObjectPointer___Int_withOriginalImplementation:(IMP)originalImplementation tweakId:(RolloutTweakId *)tweakId
{
  return ^void(id rcv, id arg0, id arg1, id arg2, int arg3) {
    void (*originalFunction)(id, SEL, id, id, id, int) = (void *) originalImplementation;
    NSArray *originalArguments = @[     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg0], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg1], 
     [[RolloutTypeWrapper alloc] initWithObjCObjectPointer:arg2], 
     [[RolloutTypeWrapper alloc] initWithInt:arg3], 
];
    
    RolloutTypeWrapper *result __attribute__((unused)) = [self->_invocation invokeWithTweakId:tweakId originalArguments:originalArguments originalMethodWrapper:^RolloutTypeWrapper *(NSArray *arguments) {
        originalFunction(rcv, NSSelectorFromString(tweakId.methodId.selector), ((RolloutTypeWrapper*)arguments[0]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[1]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[2]).objCObjectPointerValue, ((RolloutTypeWrapper*)arguments[3]).intValue); return [[RolloutTypeWrapper alloc] initWithVoid];
    }];

    
  };
}
@end
