//
//  ChartConstants.h
//  emma
//
//  Created by Xin Zhao on 13-8-16.
//  Copyright (c) 2013年 Upward Labs. All rights reserved.
//

#ifndef emma_ChartConstants_h
#define emma_ChartConstants_h

#define AMOUNT_SCALE @[@"Light", @"Medium", @"Heavy"]
#define AMOUNT_SCALE_POSITION @[@20.0f, @45.0f, @70.0f]
#define SCALE_COLOR [UIColor blackColor]
#define BOUNCE_ACCELERATE 3000.0f
#define BOUNCE_SEG_DURATION 0.02f
#define SEG_DATES_VIEW_HEIGHT 85


//Value space
#define TEMP_VALUE_UPBOUND 38.9
#define CM_VALUE_SPACE_START 0.0f
#define CM_VALUE_SPACE_LENGTH 100.0f
#define THUMB_FULL_RATIO ((TEMP_VALUE_UPBOUND - TEMP_VALUE_SPACE_START) / TEMP_VALUE_SPACE_LENGTH)

//Color
#define HORIZONTAL_LINE_COLOR UIColorFromRGB(0xbedadf)
#define TEMP_CURVE_COLOR [UIColor redColor]
#define WEIGHT_CURVE_COLOR GLOW_COLOR_GREEN 
#define CALORIE_IN_CURVE_COLOR UIColorFromRGB(0xFB8C25)
#define CALORIE_OUT_CURVE_COLOR UIColorFromRGB(0x6CB936)
#define WEIGHT_CURVE_COLOR GLOW_COLOR_GREEN
#define CM_BAR_TEX_NONE UIColorFromRGB(0xecc088)
#define CM_BAR_TEX_STICKY UIColorFromRGB(0xfda421)
#define CM_BAR_TEX_SLIPERY UIColorFromRGB(0xfc8d00)
#define CYCLE_NORMAL_COLOR [UIColor whiteColor]
#define SEX_BUBBLE_COLOR UIColorFromRGB(0xfc950b)
#define SEX_BUBBLE_COLOR_COMPS CGColorGetComponents(SEX_BUBBLE_COLOR.CGColor)
#define THUMB_BUBBLE_COLOR UIColorFromRGB(0x6971d6)
#define THUMB_BUBBLE_COLOR_COMPS CGColorGetComponents(THUMB_BUBBLE_COLOR.CGColor)

//Font size
#define DATE_LABEL_FONT_SIZE 10
#define SCALE_LABEL_FONT_SIZE 13

//Size
#define MONTH_CURVE_DOT_SIZE CGPointMake(2.0f, 4.0f)
#define WEEK_CURVE_DOT_SIZE CGPointMake(4.0f, 7.0f)
#define QUARTER_CURVE_DOT_SIZE CGPointMake(1.0f, 2.5f)
#define THUMB_CURVE_DOT_SIZE CGPointMake(0.75f, 3.0f)

//Text and enum string
#define TITLE_TEMP @"CYCLE CHART"
#define TITLE_TEMP_FOR_PARTNER @"HER CYCLE CHART"
#define TITLE_CM @"CM CHART"
#define TITLE_TEMP_CM @"BBT & CM"
#define TITLE_WEIGHT @"WEIGHT"
#define TITLE_CALORIE @"CALORIES"
#define TITLE_NUTRITION @"NUTRITION"

//Position
#define DATES_LABEL_Y_RELATIVE_TO_WHOLE_VIEW 0.05f
#define THUMB_CHART_UPBOUND_Y 0.225f
#define THUMB_CHART_TITLE_HEIGHT 36.0f
#define THUMB_BUBBLE_WIDTH 84
#define THUMB_BUBBLE_HEIGHT 20
#define BUBBLE_GAP 10
#define BUBBLE_ARROW 6
#define RANGE_LENGTH_THUMB_TO_NORMAL (3.15f / 2.0f)
#define SCALE_LABEL_START_OFFSET (5.0f)
#define SCALE_LABEL_END_OFFSET (2.0f)

//Count
#define WEEK_DAYS_PER_SCREEN 7.0
#define MONTH_DAYS_PER_SCREEN 31.0
#define QUARTER_DAYS_PER_SCREEN 92.0
#define WEEK_SEG_COUNT 18
#define MONTH_SEG_COUNT (WEEK_SEG_COUNT * WEEK_DAYS_PER_SCREEN / MONTH_DAYS_PER_SCREEN)
#define QUARTER_SEG_COUNT (WEEK_SEG_COUNT * WEEK_DAYS_PER_SCREEN / QUARTER_DAYS_PER_SCREEN)

//Chart data type order
#define CHART_DATA_TYPE_ORDER_TTC @[@(CHART_DATA_TYPE_TEMP), @(CHART_DATA_TYPE_CM), @(CHART_DATA_TYPE_TEMP_CM), @(CHART_DATA_TYPE_WEIGHT)]
#define CHART_DATA_TYPE_ORDER_TTC_WITH_3P @[@(CHART_DATA_TYPE_TEMP), @(CHART_DATA_TYPE_CM), @(CHART_DATA_TYPE_TEMP_CM), @(CHART_DATA_TYPE_WEIGHT), @(CHART_DATA_TYPE_CALORIE), @(CHART_DATA_TYPE_NUTRITION)]

#define CHART_DATA_TYPE_ORDER_NONTTC @[@(CHART_DATA_TYPE_WEIGHT), @(CHART_DATA_TYPE_TEMP), @(CHART_DATA_TYPE_CM), @(CHART_DATA_TYPE_TEMP_CM)]
#define CHART_DATA_TYPE_ORDER_NONTTC_WITH_3P @[@(CHART_DATA_TYPE_WEIGHT), @(CHART_DATA_TYPE_TEMP), @(CHART_DATA_TYPE_CM), @(CHART_DATA_TYPE_TEMP_CM), @(CHART_DATA_TYPE_CALORIE), @(CHART_DATA_TYPE_NUTRITION)]

#define CHART_DATA_TYPE_ORDER_FERTILITY @[@(CHART_DATA_TYPE_TEMP), @(CHART_DATA_TYPE_CM), @(CHART_DATA_TYPE_TEMP_CM)]
#define CHART_DATA_TYPE_ORDER_HEALTH  @[@(CHART_DATA_TYPE_WEIGHT), @(CHART_DATA_TYPE_CALORIE), @(CHART_DATA_TYPE_NUTRITION)]

//common
#define GRID_DIVIDER 22
#define BG_TEXT_SPACER 16.f
#define _PORTRAIT_GRID_AREA_RECT CGRectMake(0, 84, 320, 294);
#define GRID_AREA_HEIGHT_2_WHOLE (11.f / 12.f)

//upper
#define UPPER_H 84
#define UPPER_H_LANDSCAPE 50

//info panel
#define INFO_H 110
#define INFO_H_35 110
#define INFO_H_LANDSCAPE 68

//scale labels
#define CELSIUS_LABELS @[@36.0f, @37.111111f, @0.111111f]
#define FAHRENHEIT_INTERVAL 0.2f
#define DATE_COLOR UIColorFromRGB(0x888888)

//chart bg
#define GRID_SCREEN_X @[@0, @294, @13.363636]
#define GRID_COLOR UIColorFromRGBA(0xa8a8a8b0)
#define FERTILE_WINDOW_COLOR UIColorFromRGB(0xd0f8cb)
#define FERTILE_WINDOW_TEXT @"Fertile window"
#define FERTILE_WINDOW_TEXT_COLOR UIColorFromRGB(0x86ce7e)
#define FERTILE_WINDOW_FONT_SIZE 12
#define FERTILE_WINDOW_TEXT_RELATIVE_Y (1.f - 11.5f/12.f)
#define PERIOD_COLOR UIColorFromRGB(0xeda8c3)
#define PERIOD_TEXT_COLOR UIColorFromRGB(0xE55A8C)
#define PERIOD_TEXT @"Period"
#define BG_COLOR UIColorFromRGB(0xe5f6fe)
#define COVER_LINE_TEXT @"Cover line"
#define RECOMMENDED_INTAKE_TEXT @"Recommended intake"

//curve
#define OV_BUBBLE_COLOR UIColorFromRGB(0xee4b42)
#define OV_BUBBLE_TEXT @"Ovulation"
#define OV_BUBBLE_FONT_SIZE 12
#define DOT_RADIUS 8
#define CURVE_W 3

#define TEMP_VALUE_SPACE_START 35.944444f
#define TEMP_VALUE_SPACE_LENGTH 1.222223f
#define NORMAL_BBT_VALUE_RANGE ChartRangeMake(TEMP_VALUE_SPACE_START, TEMP_VALUE_SPACE_LENGTH)

#define TEMP_INTERVAL_SMALL 0.05
#define TEMP_INTERVAL_MEDIUM 0.1
#define TEMP_INTERVAL_LARGE 0.25
#define TEMP_INTERVAL_EVEN_LARGER 0.5

//pointer
#define POINT_SCREEN_X 279.25f 

#define CHART_DATA_TYPE_TEMP 0x01
//#define CHART_DATA_TYPE_CM 0x02
//#define CHART_DATA_TYPE_TEMP_CM 0x03
#define CHART_DATA_TYPE_WEIGHT 0x04
#define CHART_DATA_TYPE_CALORIE 0x08
#define CHART_DATA_TYPE_NUTRITION 0x10

//nutritio pie chart
#define PIE_DIAMETER_2_BOUND 0.65f


typedef enum{
    ChartDateRangeTypeMonth = 0,
    ChartDateRangeTypeWeek,
    ChartDateRangeTypeQuarter,
} ChartDateRangeType;

#endif
