source 'git@github.com:upwlabs/PodsSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

mode_dev = 'dev'
mode_test = 'test'
mode_release = 'release'

config_file = './LocalPodfile.rb'
require config_file if File.file? config_file

POD_CURRENT_MODE ||= mode_release
POD_DEV_ROOT ||= ENV['POD_DEV_ROOT']

puts 'CURRENT MODE: ' + POD_CURRENT_MODE


def common_pods
    pod 'UICKeyChainStore', '2.0.6'
    pod 'FormatterKit', '1.5.3'
    pod 'TTTAttributedLabel', '1.10.1'
    pod 'Facebook-iOS-SDK', '3.17.0'
    pod 'CardIO', '5.1.0'
    pod 'SZTextView', '1.1.10'
    pod 'AppsFlyer-SDK', '3.3.0'
    pod 'ZipArchive', '1.4.0'
    pod 'XYPieChart', '0.2'
    pod 'UPPlatformSDK', '1.1.5.8'
    pod 'DACircularProgress', '2.3.1'
    pod 'AMScrollingNavbar', '1.3.8'
    pod 'ZXingObjC', '3.1.0'
    pod 'Rollout.io', '0.10.2'
    pod 'UIDeviceUtil', '1.1.2'
    
    #--private pods begins
    if (POD_CURRENT_MODE == 'dev')
        if (!POD_DEV_ROOT)
            puts 'POD_DEV_ROOT not defined, please set POD_DEV_ROOT in LocalPodfile.rb or export POD_DEV_ROOT in your rc file first'
        end
        pod 'GLFoundation', :path => POD_DEV_ROOT + '/GLFoundation-iOS'
        pod 'GLCommunity', :path => POD_DEV_ROOT + '/GLCommunity-iOS'
        pod 'GLPeriodEditor', :path => POD_DEV_ROOT + '/GLPeriodEditor'
        pod 'GLQuestionKit', :path => POD_DEV_ROOT + '/GLQuestionKit-iOS'
    elsif (POD_CURRENT_MODE == 'test')
        pod 'GLFoundation', :git => 'git@github.com:upwlabs/GLFoundation-iOS.git', :branch => 'master'
        pod 'GLCommunity', :git => 'git@github.com:upwlabs/GLCommunity-iOS.git', :branch => 'master'
        pod 'GLPeriodEditor', :git => 'git@github.com:upwlabs/GLPeriodEditor.git', :branch => 'master'
        pod 'GLQuestionKit', :git => 'git@github.com:upwlabs/GLQuestionKit-iOS.git', :branch => 'master'
    else
        pod 'GLFoundation', '1.4.2'
        pod 'GLCommunity', '2.0'
        pod 'GLPeriodEditor', '1.2.0'
        pod 'GLQuestionKit', '1.4.0'
    end
    #--private pods ends
end

target 'emma' do
    common_pods
end

target 'emma WatchKit Extension' do
    common_pods
end

target 'shareExtension', :exclusive => true do
    pod 'libextobjc/EXTScope', '0.4.1'
    pod 'hpple', '0.2.0'
    pod 'UICKeyChainStore', '2.0.6'
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
        end
    end
end
